### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by LBEILC** [hhhh218/Neko#1]
![image](https://github.com/user-attachments/assets/0169ee39-e715-402b-ac39-4f86e0957492)
插件配置如下
![image](https://github.com/user-attachments/assets/f1ddf89b-55d5-4467-a330-01881cd4babe)

**Comment by hhhh218** [comment]
影响正常使用吗，似乎是session.author.user.id引起的问题，下个版本会连带着一起修复

**Comment by LBEILC** [comment]
似乎没法使用，在沙盒测试了一下，报错之后机器人没有任何输出

**Comment by hhhh218** [comment]
沙盒建个群试试，这个应该不影响使用，我编译后测试过

**Comment by hhhh218** [comment]
还没反应的话日志发来看看

**Comment by LBEILC** [comment]
> 还没反应的话日志发来看看

 TypeError: Cannot read properties of undefined (reading 'id')
                            at Proxy.<anonymous> (C:\Users\12449\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-neko\lib\index.js:305:73)
                            at Object.apply (C:\Users\12449\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:393:23)
                            at Proxy.dispatch (C:\Users\12449\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:490:27)
                            at dispatch.next (<anonymous>)
                            at Function.from (<anonymous>)
                            at Proxy.emit (C:\Users\12449\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:497:11)
                            at QQBot.dispatch (C:\Users\12449\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:338:20)
                            at WebSocket.<anonymous> (C:\Users\12449\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\adapter-qq\lib\index.cjs:528:31)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            
                            日志如上，沙盒中创建群聊的话没反应

**Comment by hhhh218** [comment]
只有一个报错吗

**Comment by LBEILC** [comment]
> 只有一个报错吗

![image](https://github.com/user-attachments/assets/6d0a63b4-10b9-4d13-b242-302da89b0ff6)
完整日志如上，就这一个报错

**Comment by hhhh218** [comment]
我向npm推送了1.2.0版本，你可以等会在koishi插件商店更新后使用新版本试试

**Comment by LBEILC** [comment]
> 我向npm推送了1.2.0版本，你可以等会在koishi插件商店更新后使用新版本试试

今天更新了1.2.1版本，还是出现同样的报错，这个和我使用的是qq官方接口适配器有关系吗
![image](https://github.com/user-attachments/assets/c3bf3b5a-b0a6-4499-a636-40fde59d726b)

**Comment by hhhh218** [comment]
这个我不清楚，插件启动时应输出两条日志，可能你的插件未能正常安装或加载

**Comment by kisara71** [comment]
我这貌似也是类似的问题
![image](https://github.com/user-attachments/assets/a4e5eb10-735e-4863-ad31-4f406e9a0fc4)
